Repository ml-tooling/contaxy, pull requests merged in 2022-02, with the labels that each got.

#49 Fix remote endpoint integration tests
  backend/src/contaxy/managers/auth.py
  backend/src/contaxy/managers/deployment/manager.py
  backend/src/contaxy/managers/project.py
  backend/tests/test_auth_operations.py
  backend/tests/test_deployment_operations.py
  backend/tests/test_extensions_operations.py
  backend/tests/test_file_operations.py
  backend/tests/test_json_db_operations.py
  backend/tests/test_project_operations.py
Labels: bug

#51 Add endpoints for listing, adding and deleting permissions
  backend/src/contaxy/api/endpoints/auth.py
  backend/src/contaxy/schema/shared.py
Labels: feature

#53 Refactor deployment manager to use DB as source for all service metadata.
  backend/src/contaxy/managers/components.py
  backend/src/contaxy/managers/deployment/docker.py
  backend/src/contaxy/managers/deployment/docker_utils.py
  backend/src/contaxy/managers/deployment/kube_utils.py
  backend/src/contaxy/managers/deployment/kubernetes.py
  backend/src/contaxy/managers/deployment/manager.py
  backend/src/contaxy/managers/deployment/utils.py
  backend/src/contaxy/managers/extension.py
  backend/src/contaxy/operations/deployment.py
  backend/src/contaxy/schema/deployment.py
  backend/src/contaxy/schema/shared.py
  backend/src/contaxy/utils/utils.py
  backend/tests/test_deployment_operations.py
Labels: refactoring

#55 Fix service delation not deleting the named service volume, even if delete_volumes is set to true
  backend/src/contaxy/managers/deployment/docker.py
  backend/src/contaxy/managers/deployment/docker_utils.py
  backend/tests/test_deployment_operations.py
Labels: bug

#56 Allow passing parameters to deployment actions
  backend/src/contaxy/api/endpoints/deployment.py
  backend/src/contaxy/clients/deployment.py
  backend/src/contaxy/managers/deployment/manager.py
  backend/src/contaxy/operations/deployment.py
  backend/src/contaxy/schema/shared.py
Labels: feature
